{% set version = '0.9-35' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmtest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmtest_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lmtest_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lmtest/lmtest_{{ version }}.tar.gz
  sha256: 2f4982f1b6cd133ef36fe9718f4ff2f4fa5c20716100fdd5ee5c947b68c8eb80

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-zoo

  run:
    - r-base
    - r-zoo

test:
  commands:
    - $R -e "library('lmtest')"  # [not win]
    - "\"%R%\" -e \"library('lmtest')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lmtest
  license: GPL (>= 2)
  summary: A collection of tests, data sets, and examples for diagnostic checking in linear regression
    models. Furthermore, some generic tools for inference in parametric models are provided.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
