{% set version = '0.9-36' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmtest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmtest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lmtest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lmtest/lmtest_{{ version }}.tar.gz
  sha256: be9f168d6554e9cd2be0f9d8fc3244f055dce90d1fca00f05bcbd01daa4ed56b

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-zoo
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-zoo

test:
  commands:
    - $R -e "library('lmtest')"           # [not win]
    - "\"%R%\" -e \"library('lmtest')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lmtest
  license: GPL-2 | GPL-3
  summary: A collection of tests, data sets, and examples for diagnostic checking in linear regression
    models. Furthermore, some generic tools for inference in parametric models are provided.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
