appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: IG43u4E7B4mtQGFIzdbaVDvALQzH1lQ2e/a0ojdn6bKj7zzNmThBWjjxQi6CAdkoVq9ebI7u3c40uHfDviDPT2LuN0s1EcRCUHJl6JrJBIsn3RSiTKJTTvP3NtB0AacA70IlBa41zqRFa1cPj4CSHwUj5sqGc6m6H9WwIVZ2JjrOhEvDKbKSBS38v5XPWNlRMTe3V7NeHUClWah2jIIxfgB9FsWxNHI9aaeEp9EllJc3XVW6P+8vHDV7qimH3T2dELr5PSCzsIQJARQyk+ybITYh9qxOb4tq1AlfiRjvVHiC84oZEDuEm2h0GlLDyhgmxEUT2A/GQoPmCNBue9vm6Gk3e7YXO2e7KfmdsJBsR65S8JlLIuysI7boknlz+F4nmq2HsA1Mo+DJE+Kkn5LYbWihFef/mu/MfZjYw0Y+NTiSlIrsKdfV2ghB/4CetNaEk7cVM/pPUDRTiQhUndzDoLE2j2PFMdzeDSrlXri8SWq4+S2UUe1OtFwJBDbLZwdmgBfHQ7ZNpokT4yieTcCy8ZoBGx3FHNzsecSpMy3n0DW9AbhhB/kbj7aNcPRTFXtOtfpTUhUPWKQaWad86a8fvBoKxVVUIXlK3WG/wCck9qW3QNQ44bpE+MQNrTefft99EDyZeB4GkdpAaWej3OVeK8XtKtfJHrhtckAh6QvV+SM=}
bot:
  automerge: true
